export const repetitors = [
  {
    id: 0,
    firstName: "Ольга",
    lastName: "Васина",
    subject: "Английский язык",
    img: "./img/woman1.jpg",
    examE: true,
    examO: false,
  },
  {
    id: 1,
    firstName: "Анна",
    lastName: "Волкова",
    subject: "Русский язык",
    img: "./img/woman2.jpg",
    examE: false,
    examO: true,
  },
  {
    id: 2,
    firstName: "Василиса",
    lastName: "Петрова",
    subject: "Математика",
    img: "./img/woman3.jpg",
    examE: false,
    examO: true,
  },
  {
    id: 3,
    firstName: "Елена",
    lastName: "Любина",
    subject: "Химия",
    img: "./img/woman4.jpg",
    examE: true,
    examO: true,
  },
  {
    id: 4,
    firstName: "Елена",
    lastName: "Любина",
    subject: "Химия",
    img: "./img/woman4.jpg",
    examE: false,
    examO: false,
  },
];
